feat: airlines
LukiMaurojorge/flight-agency pull request #2
Opened 2024-03-15 19:23 UTC by LukiMaurojorge

2024-03-15 21:06 UTC, gianfranco-rocco requested changes

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Http/Controllers/CreateAirlineController.php
> +    }
```suggestion
    public function __invoke(CreateAirlineRequest $request): JsonResponse
    {
        $airline = Airline::create($request->validated());
        
        return response()->json($airline, JsonResponse::HTTP_CREATED);
    }
```
Having an action for a single line of code doesn't make much sense. Actions make sense when there's a substantial amount of code that needs to be executed in order for something to happen. This is because if I were to perform said action in more than one place, I can use the action instead of duplicating code. In this particular case, all we're doing is calling `Airline::create()`, which is something you can perfectly repeat as it involves the same amount (actually, less, because you're not importing additional files) of lines as if you had an action.

As for the controller response. For APIs such as this one wich creates a resource, we tend to respond with what was created (an airline in this case). The `JsonResponse::HTTP_CREATED` equals to the HTTP status code 201 (created). Every time you need a status code make sure you don't hardcode the number, but rather use the publicly accessible constants provided by the `JsonResponse` and `Response` Illuminate classes.

Don't forget to delete the action.

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Http/Controllers/DeleteAirlineController.php
> +    }
```suggestion
    public function __invoke(Airline $airline): JsonResponse
    {
        $airline->delete();
        
        return response()->noContent();
    }
```
Remember to leverage Laravel's features whenever possible. In this case, [Route Model Binding](https://laravel.com/docs/10.x/routing). As for the action, same thing as in the `CreateAirlineController`. 
What the `response()->noContent()` does is generate a response with no content and the 204 HTTP status code. I personally do this for delete APIs as there's not much to be said after deleting something. The response may vary depending on the project and such.

2024-03-15 21:06 UTC, gianfranco-rocco commented on Domain/Airline/Actions/CreateAirlineAction.php
Action can be deleted. See explanation in comment from `CreateAirlineController`.

2024-03-15 21:06 UTC, gianfranco-rocco commented on Domain/Airline/Actions/DeleteAirlineAction.php
Action can be deleted.

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Http/Controllers/GetAirlineController.php
> +    }
```suggestion
    public function __invoke(): View
    {
        $airlines = Airline::paginate(10);
        
        return view('airline', [
            'airlines' => $airlines
        ]);
    }
```
The `GetAirlineAction` isn't quite right. On the one hand, same as in the explanation in the `CreateAirlineController,` it's too little code to need action. On the other hand, actions shouldn't be responsible for returning views; that's something a controller should be responsible for. In this case, if we did need an action, it should return the data needed by the view but not the view itself.

The `View` is this one from `Illuminate\Contracts\View`, btw.

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Http/Middleware/VerifyCsrfToken.php
> +        '/airline/create'
Hmmm, why this? You should provide the CSRF token for the API to work.

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Http/Controllers/UpdateAirlineController.php
> +    }
```suggestion
    public function __invoke(UpdateAirlineRequest $request, Airline $airline): JsonResponse
    {
        $airline->update($request->validated())
    
        return response()->json($airline);
    }
```
The `update` method returns a boolean, that's why I'm returning the `$airline` instead of the result from the method in the suggestion.
As for the FormRequest, you should definitely have a different one because there's a difference between them (See comments in the `CreateAirlineRequest` to learn more about the difference).

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Http/Requests/CreateAirlineRequest.php
> +    }
```suggestion
    {
        return [
            'name' => [
                'required',
                'string',
                Rule::unique(Airline::class)
            ],
            'description' => ['required', 'string']
        ];
    }
```
Here at Light-it, we use the array-based syntax for validation rules (I formatted the first set of rules into different lines for easier readability). There are a couple of pros to this:
1. It's more easily readable IMO
2. For cases where you need to use the `Rule` class for more custom rules, array-based rules are the way to go

Besides the `CreateAirlineRequest`, you should create the `UpdateAirlineRequest` for the `UpdateAirlineController` to use. The difference will be just the following:
```
// Instead of 
Rule::unique(Airline::class)

// You should do
Rule::unique(Airline::class)->ignore($this->route('airline'))
```

To understand in more depth what's going on in the suggestion to use the `Rule` class, refer to the "Forcing a Unique Rule to Ignore a Given ID:" subsection in [here](https://laravel.com/docs/10.x/validation#rule-unique). The basic explanation is that you must exclude the unique validation for the name of the current airline being updated. Otherwise, if you were to submit the form with the same name the airline already has, it would fail because the name is already being used (by the airline itself).

The reason why I did `Rule::unique(Airline::class)` instead of `Rule::unique('airlines')` is because Laravel is so well thought out that if you pass the fully qualified class name (learn more about what that is right [here](https://www.php.net/manual/en/language.namespaces.rules.php)) of a model to the method, it will take care of figuring out what the name of the table is (basically every method that's related to DB stuff allows you do to stuff like this). I find doing this better than manually typing out the table name.

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Models/Airline.php
> +
```suggestion
```
No need for the `HasFactory` trait to be used. This is because we don't use factories through models but use the factory class itself. What I mean is:
```
// No 
Airline::factory()->create();

// Yes
AirlineFactory::new()->create();
```

2024-03-15 21:06 UTC, gianfranco-rocco commented on app/Providers/AppServiceProvider.php
> +        });
```suggestion
        //
```
This code is nice, but it needs to be used correctly. Binding is helpful for telling the framework how an interface should be resolved (meaning, an instance of which class should be provided when injecting that interface as a dependency). In this case, `CreateAirlineAction` isn't an interface but a class, so you don't need to tell the framework how to resolve it.

2024-03-15 21:06 UTC, gianfranco-rocco commented on composer.json
> +            "Domain\\": "Domain/"
Cool that you figured this out on your own!!

2024-03-15 21:06 UTC, gianfranco-rocco commented on database/migrations/2024_02_22_172124_create_city_table.php
This change isn't wrong, considering that this project isn't deployed anywhere. However, we should never change migrations that have already been pushed to production because they've already been run. In production, only new migrations are run, meaning that this change wouldn't be applied, and the app could potentially break, resulting in either mad clients or money loss (if the project manages money). Next time, if you need to change something like this (or could be changing a column's name, type, adding new columns, etc.) do it by creating new migrations instead.

2024-03-15 21:06 UTC, gianfranco-rocco commented on database/migrations/2024_02_22_173332_create_airline_table.php
Same thing here.

2024-03-15 21:06 UTC, gianfranco-rocco commented on database/migrations/2024_02_22_173442_create_flight_table.php
Same thing here.

2024-03-15 21:06 UTC, gianfranco-rocco commented on database/seeders/DatabaseSeeder.php
> +        // UserFactory::new()->create()->count();
```suggestion
```
Ideally, this code shouldn't be part of the PR changes, given that it's commented.

2024-03-15 21:06 UTC, gianfranco-rocco commented on resources/js/airline.js
> +    let description = document.getElementById("description").value;
```suggestion
    const name = document.getElementById("name").value;
    const description = document.getElementById("description").value;
```
When variables don't change, use `const` instead of `let`.

2024-03-15 21:06 UTC, gianfranco-rocco commented on routes/api.php
> +    Route::put('/{airline}', UpdateAirlineController::class);
```suggestion
Route::prefix('airlines')->group(function () {
    Route::post('/', CreateAirlineController::class);
    
    Route::prefix('{airline}')->group(function () {
        Route::put('/', UpdateAirlineController::class);
        Route::delete('/', DeleteAirlineController::class);
    });
```
Instead of pushing commented code, it's better to delete it altogether.

You can group by prefix, too, even when using Route Model Binding.

Note that I changed the prefix of the parent group of all of these routes from `airline` to `airlines`. I did this because the prefixes tend to be plural instead of singular.

2024-03-15 21:06 UTC, gianfranco-rocco commented on routes/channels.php
> +// });
Instead of commenting, it's better to delete.

2024-03-15 21:06 UTC, gianfranco-rocco commented on routes/console.php
> +// })->purpose('Display an inspiring quote');
Noo, not the inspire command 😢

2024-03-15 21:06 UTC, gianfranco-rocco commented on routes/web.php
> +Route::get('/airline', GetAirlineController::class);
```suggestion
Route::get('/airlines', GetAirlinesController::class);
```
Notice I pluralized both the prefix and the controller name (`Airline` to `Airlines`).

2024-03-15 21:06 UTC, gianfranco-rocco commented on tailwind.config.js
> +        "./resources/**/*.vue",
```suggestion
        "./resources/**/*.{js,vue,blade.php}",
```
I'm pretty sure you can do this.

2024-03-15 21:06 UTC, gianfranco-rocco commented on resources/views/home.blade.php
> +
No body?

2024-03-15 21:06 UTC, gianfranco-rocco commented on resources/views/header.blade.php
> +        <a href="#" class="p-2 lg:px-4 md:mx-2 text-white rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300">Flights</a>
```suggestion
        <a href="/airline" class="p-2 lg:px-4 md:mx-2 text-white rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300">Airlines</a>
```
Given the fact that the other 2 modules aren't developed yet, skip them from the navigation bar.

2024-03-15 21:06 UTC, gianfranco-rocco commented on resources/views/home.blade.php
> +    @vite(['resources/js/airline.js'])
```suggestion
```
This file is already being imported in the `airline.blade.php`.

2024-03-15 21:06 UTC, gianfranco-rocco commented on resources/views/airline.blade.php
> +<body class="h-full">
Everything except `@vite(['resources/js/airline.js'])` and the body content should be inside a layout. Go [here](https://laravel.com/docs/10.x/blade#layouts-using-template-inheritance) to learn how to implement and use one.

2024-03-18 18:34 UTC, LukiMaurojorge commented on resources/views/home.blade.php
> +
this is for a future

2024-03-20 17:33 UTC, LukiMaurojorge commented on zsh-syntax-highlighting
I don't know what's this jajajja

2024-03-21 20:25 UTC, gianfranco-rocco requested changes

2024-03-21 20:25 UTC, gianfranco-rocco commented on app/Http/Controllers/GetAirlineController.php
This should be `GetAirlinesController` (note `AirlineS` and not `Airline`) because otherwise when I read `GetAirlineController`, I expect it's a controller used for getting a specific airline. But, in reality, that's not what it does. Controller names should convey exactly what they do to prevent this.

2024-03-21 20:25 UTC, gianfranco-rocco commented on app/Http/Controllers/GetAirlineController.php
> +class GetAirlineController extends Controller
```suggestion
class GetAirlinesController extends Controller
```

2024-03-21 20:25 UTC, gianfranco-rocco commented on app/Http/Controllers/GetAirlineController.php
> +        return view('airline', [
```suggestion
        return view('airlines', [
```

2024-03-21 20:25 UTC, gianfranco-rocco commented on database/factories/AirlineFactory.php
> +            'description' => Str::random(10)
```suggestion
            'description' => fake()->text()
```

2024-03-21 20:25 UTC, gianfranco-rocco commented on database/seeders/AirlineSeeder.php
> +        Airline::factory()->count(15)->create();
```suggestion
        AirlineFactory::new()->count(15)->create();
```
Remember that we should interact directly with the factory class, not via a method in the model.

2024-03-21 20:25 UTC, gianfranco-rocco commented on resources/views/home.blade.php
> +
Hmm 🤔

2024-03-21 20:25 UTC, gianfranco-rocco commented on routes/api.php
> +
```suggestion
```
No commented code should be pushed.

2024-03-21 20:25 UTC, gianfranco-rocco commented on zsh-syntax-highlighting
A virus most likely (?

2024-03-22 19:32 UTC, LukiMaurojorge commented on database/seeders/DatabaseSeeder.php
> +        // UserFactory::new()->create()->count();
I didn't have this in my local

2024-03-22 19:41 UTC, LukiMaurojorge commented on zsh-syntax-highlighting
jajaja It's because I configured the terminal but I don't know why is here

2024-03-25 20:56 UTC, gianfranco-rocco requested changes

2024-03-25 20:56 UTC, gianfranco-rocco commented on app/Http/Controllers/UpdateAirlineController.php
> +    public function __invoke(CreateAirlineRequest $request, Airline $airline): JsonResponse
You're still using the `CreateAirlineRequest`. You should create and use a different Form Request that follows what's explained in [this](https://github.com/LukiMaurojorge/flight-agency/pull/2#discussion_r1526803980) comment.

2024-03-25 20:56 UTC, gianfranco-rocco commented on app/Providers/AppServiceProvider.php
> +use Illuminate\Contracts\Foundation\Application;
```suggestion
use Illuminate\Support\ServiceProvider;
```
These classes are not being used.

2024-04-02 16:48 UTC, gianfranco-rocco approved these changes
LGTM!

2024-04-02 20:01 UTC, merged